version: '3'

services:
  api:
    build: ./
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
